/**
  @file
  @brief Datalines for BE_VALIDA_GRUPO dataset
  @details Generated by %mp_ds2cards()
    Source: https://github.com/sasjs/core
  @cond 
**/
data work.BE_VALIDA_GRUPO ;
attrib 
VLD_UID                          length= 8      format=9. label="VLD_UID"
GRP_CODIGO                       length= $10    format=$10. label="GRP_CODIGO"
VLD_FILENAME                     length= $50    format=$50. label="VLD_FILENAME"
VLD_DIRECTORIO                   length= $50    format=$50. label="VLD_DIRECTORIO"
VLD_USER_CREADO                  length= $50    format=$50. label="VLD_USER_CREADO"
VLD_DATE_CREADO                  length= 8      format=DATETIME27.6 label="VLD_DATE_CREADO"
VLD_ESTADO                       length= 8      format=2. label="VLD_ESTADO"
VLD_VERSION                      length= 8      format=5.2 label="VLD_VERSION"
;
infile cards dsd;
input 
  VLD_UID
  GRP_CODIGO                       :$char.
  VLD_FILENAME                     :$char.
  VLD_DIRECTORIO                   :$char.
  VLD_USER_CREADO                  :$char.
  VLD_DATE_CREADO
  VLD_ESTADO
  VLD_VERSION
;
missing a b c d e f g h i j k l m n o p q r s t u v w x y z _;
datalines4;
2,GRPCTRL00,,Semanal,gschade,2007201484.95179,1,1
4,GRPCTRL01,,Semanal,gschade,2007201508.75968,1,1
8,GRPCTRL03,,Semanal,gschade,2007201575.76495,1,1
10,GRPCTRL04,,Semanal,gschade,2007201627.45965,1,1
12,GRPCTRL05,,Semanal,gschade,2007201678.37604,1,1
14,GRPCTRL06,,Semanal,gschade,2007201708.55018,1,1
6,GRPCTRL02,,Semanal,gschade,2007201552.40999,1,1
15,GRPCTRL06,grpctrl06.sas,Semanal,gschade,2007204159.5,1,1.01
19,GRPCTRL01,grpctrl01.sas,Semanal,gschade,2007210467.1,1,1.01
20,GRPCTRL02,grpctrl02.sas,Semanal,gschade,2007210494.9,1,1.01
21,GRPCTRL03,grpctrl03.sas,Semanal,gschade,2007210515,1,1.01
16,GRPCTRL00,grpctrl00.sas,Semanal,gschade,2007209860.2,1,1.01
17,GRPCTRL05,grpctrl05.sas,Semanal,gschade,2007209863.3,1,1.01
;;;;
run;
/** @endcond **/
